#Site settings
title: Do Something Good
email: riceshiro@hotmail.com
description: "UI Design // Graphic Design // Visual Communication Design // Web Design"

# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested